In [64]:
import os
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm

In [65]:
# loading the data from csv file. it contains the image name and category
"""
0 - anger
1 - contempt
2 - disgust
3 - fear
4 - happy 
5 - sadness
6 - surprise
""" 
train = pd.read_csv('faces/train.csv')

print(train.shape)
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(train)

(981, 2)
      id  label
0      1      0
1      2      0
2      3      0
3      4      0
4      5      0
5      6      0
6      7      0
7      8      0
8      9      0
9     10      0
10    11      0
11    12      0
12    13      0
13    14      0
14    15      0
15    16      0
16    17      0
17    18      0
18    19      0
19    20      0
20    21      0
21    22      0
22    23      0
23    24      0
24    25      0
25    26      0
26    27      0
27    28      0
28    29      0
29    30      0
30    31      0
31    32      0
32    33      0
33    34      0
34    35      0
35    36      0
36    37      0
37    38      0
38    39      0
39    40      0
40    41      0
41    42      0
42    43      0
43    44      0
44    45      0
45    46      0
46    47      0
47    48      0
48    49      0
49    50      0
50    51      0
51    52      0
52    53      0
53    54      0
54    55      0
55    56      0
56    57      0
57    58      0
58    59      0
59    60      0
60    61      0

In [66]:
# load in the images as numpy arrays into a list
train_image = []
# tqdm displays a progress bar. its just for convenience
for i in tqdm(range(train.shape[0])):
    # the images are grayscale, with a resolution of 48x48 and we store the pixel value between 0 and 1, default is 0-255
    img = image.load_img('faces/train/'+train['id'][i].astype('str')+'.png', target_size=(48,48,1),
    color_mode='grayscale')
    img =  image.img_to_array(img)
    img = img/255
    train_image.append(img)
print(train_image)

,
        [0.23529412],
        ...,
        [0.45490196],
        [0.4509804 ],
        [0.45490196]],

       [[0.26666668],
        [0.25882354],
        [0.24705882],
        ...,
        [0.4627451 ],
        [0.4627451 ],
        [0.4627451 ]],

       [[0.23921569],
        [0.2509804 ],
        [0.23921569],
        ...,
        [0.4627451 ],
        [0.46666667],
        [0.46666667]],

       ...,

       [[0.31764707],
        [0.31764707],
        [0.32941177],
        ...,
        [0.4       ],
        [0.3882353 ],
        [0.39215687]],

       [[0.31764707],
        [0.32156864],
        [0.3254902 ],
        ...,
        [0.39215687],
        [0.39607844],
        [0.4       ]],

       [[0.30980393],
        [0.31764707],
        [0.3254902 ],
        ...,
        [0.40392157],
        [0.40784314],
        [0.40392157]]], dtype=float32), array([[[0.30588236],
        [0.28627452],
        [0.2509804 ],
        ...,
        [0.4509804 ],
        [0.44705883],
        

In [67]:
# store the list as a numpy array for the input data
X = np.array(train_image)
print(X)

[[[[0.09411765]
   [0.03921569]
   [0.05098039]
   ...
   [0.13725491]
   [0.6392157 ]
   [0.972549  ]]

  [[0.06666667]
   [0.03529412]
   [0.06666667]
   ...
   [0.05490196]
   [0.39607844]
   [0.92156863]]

  [[0.03921569]
   [0.04705882]
   [0.06666667]
   ...
   [0.01568628]
   [0.16862746]
   [0.7882353 ]]

  ...

  [[0.87058824]
   [0.8784314 ]
   [0.8784314 ]
   ...
   [0.6039216 ]
   [0.60784316]
   [0.61960787]]

  [[0.89411765]
   [0.8980392 ]
   [0.8980392 ]
   ...
   [0.59607846]
   [0.60784316]
   [0.61960787]]

  [[0.91764706]
   [0.92156863]
   [0.9137255 ]
   ...
   [0.5882353 ]
   [0.6       ]
   [0.6117647 ]]]


 [[[0.06666667]
   [0.03921569]
   [0.0627451 ]
   ...
   [0.08235294]
   [0.53333336]
   [0.9529412 ]]

  [[0.04705882]
   [0.04705882]
   [0.07058824]
   ...
   [0.03529412]
   [0.3019608 ]
   [0.8627451 ]]

  [[0.03529412]
   [0.0627451 ]
   [0.06666667]
   ...
   [0.01568628]
   [0.12156863]
   [0.6901961 ]]

  ...

  [[0.8666667 ]
   [0.8745098 ]
   [0.8

In [68]:
y = train['label'].values
print(y)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 

In [69]:
y = to_categorical(y)
print(y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [70]:
# we split the data into train and test sets for valiadtion
# the split is random. random_state is a seed for psuedo random numbers and test_size is the % of test data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3)


In [71]:
""" 
The Model for deep learning is defined here
It has a simple architecture with 2 convolutional layers, one dense hidden layer and an output layer.
"""
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu',input_shape=(48,48,1)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='Adam',
              metrics=['accuracy'])


In [72]:
#training the model
model.fit(X_train, y_train, epochs=25, validation_data=(X_test, y_test))

Train on 686 samples, validate on 295 samples
Epoch 1/25
686/686 [==============================] - 5s 7ms/step - loss: 1.7166 - accuracy: 0.3717 - val_loss: 1.2675 - val_accuracy: 0.6576
Epoch 2/25
686/686 [==============================] - 4s 6ms/step - loss: 1.1007 - accuracy: 0.6268 - val_loss: 0.6172 - val_accuracy: 0.8407
Epoch 3/25
686/686 [==============================] - 4s 6ms/step - loss: 0.6356 - accuracy: 0.8017 - val_loss: 0.3577 - val_accuracy: 0.9119
Epoch 4/25
686/686 [==============================] - 4s 6ms/step - loss: 0.4240 - accuracy: 0.8673 - val_loss: 0.3204 - val_accuracy: 0.9254
Epoch 5/25
686/686 [==============================] - 4s 6ms/step - loss: 0.2775 - accuracy: 0.9169 - val_loss: 0.2074 - val_accuracy: 0.9458
Epoch 6/25
686/686 [==============================] - 4s 6ms/step - loss: 0.2267 - accuracy: 0.9052 - val_loss: 0.1834 - val_accuracy: 0.9492
Epoch 7/25
686/686 [==============================] - 4s 6ms/step - loss: 0.1644 - accuracy: 0.9475 - 

In [73]:
from keras.models import model_from_json
# serialize model to JSON
model_json = model.to_json()
with open("model/model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model/model.h5")
print("Saved model to disk")

Saved model to disk
